Read data from mysql we need some specific import for instance sqlalchemy

In [6]:
import pandas as pd
from sqlalchemy import create_engine

In [11]:
engine = create_engine('mysql+pymysql://root:test@localhost/social')

In [13]:
sqldf=pd.read_sql('select * from users',con=engine)

In [14]:
sqldf

,id,username,email,password,name,coverPic,profilePic,city,website
0,1,test,test@gmail.com,$2a$10$IxFYHW3Byk9xLW..4NN7gOGua6NAdDI14erka0p...,Mwikali M,1686344692682vegetables-fruits-white_55883-892...,1686342538134male.png,None,None
1,2,test2,test2@gmail.com,$2a$10$.caoC36BDRTYU60x4jogAenOFR0fJWdSi.BfP4L...,Test2,https://images.pexels.com/photos/7467913/pexel...,https://images.pexels.com/photos/7468239/pexel...,SA,sandy.dev
2,3,test3,test3@gmail.com,$2a$10$mHybinYMgDNCZX3jKZlCtudRlEkK4xRG27ApyRw...,Sane Roe,None,None,None,None
3,4,tester,tester@gmail.com,$2a$10$ofSA8jwvGheKXR8wiMjtnOrAKeEPAbb5XGc9g2W...,Tester,None,None,None,None
4,5,console,tester@console.com,$2a$10$ndO1rgKTFz9LUZGfONinOuPVS58PAYkbnn7xKSd...,Console,None,None,None,None
5,6,starixc,starixc@gmail.com,$2a$10$pDbQ47XdHWaVzZY4xoTA2e3bdH5X/MoYcJtonUt...,Account,None,None,None,None
6,7,Evans,evans@test.com,$2a$10$2hrUr3.2kMMRb9N7K2tCwO1aeOLXT54NJsMn2Xt...,Evans,1686226477412female.png,1686226477393vegetables-fruits-white_55883-892...,Kenya,www.evs.co.ke
7,8,Chris,chtis@test.com,$2a$10$S.wyp05BDjpnLbhcbk43qOv8XH4L3usx6NBb2Um...,Chris,1686379909435vegetables-fruits-white_55883-892...,1686379909411female.png,None,www.chris.org
8,9,,,$2a$10$wCwLHLjGu7j2StowIVil8.RgMU44KaLO3oG4XeJ...,,None,None,None,None
9,10,test19,test19@gmail.com,$2a$10$mrnygX/d0D1z5NHW2wGbs.bo6fSD5SM1pxLSY2S...,Test19,None,None,None,None